function PMSBYJSON() {
  return {
    branch: '',
    sb_account_no: '',
    state: 1,
    date: '',
    master_policy_no: '',
    //Customer Name Fields
    title_account_holder: '',
    fname_account_holder: '',
    mname_account_holder: '',
    lname_account_holder: '',
    //Communication Fields
    mobile_account_holder: '',
    gender_account_holder: '',
    email_account_holder: '',
    // PAN, Aadhar, Disability Fields
    pan_account_holder: '',
    aadhar_account_holder: '',
    disability_account_holder: '',
    disability_details_account_holder: '',
    //DOB Fields
    dob_account_holder: '',
    age_account_holder: '',
    //Corrospondence Address Fields
    address_account_holder: '',
    city_account_holder: '',
    district_account_holder: '',
    pin_account_holder: '',
    state_account_holder: '',
    country_account_holder: '',
    //Nominee Fields
    title_nominee: '',
    fname_nominee: '',
    mname_nominee: '',
    lname_nominee: '',
    mobile_nominee: '',
    email_nominee: '',
    relationship_nominee: '',
    other_relationship_nominee: '',
    dob_nominee: '',
    age_nominee: '',
    minor_nominee: '',
    gender_nominee: '',
    aadhar_nominee: '',
    nominee_addr_same_as_acc_holder: '',
    address_nominee: '',
    city_nominee: '',
    district_nominee: '',
    pin_nominee: '',
    state_nominee: '',
    country_nominee: '',
    title_guardian: '',
    fname_guardian: '',
    mname_guardian: '',
    lname_guardian: '',
    relationship_guardian: '',
    other_relationship_guardian: '',
    dob_guardian: '',
    mobile_guardian: '',
    address_guardian: '',
    city_guardian: '',
    district_guardian: '',
    pin_guardian: '',
    state_guardian: '',
    country_guardian: '',
  };
}

export default PMSBYJSON;
